# Generated by Django 3.1.7 on 2021-03-16 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('text', models.TextField(max_length=5000, verbose_name='Текст статьи')),
                ('slug', models.SlugField()),
                ('time_create', models.DateField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=True, verbose_name='ПУбликовать?')),
                ('version', models.IntegerField(default=0)),
            ],
        ),
    ]
