# Generated by Django 3.1.7 on 2021-03-16 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wikisite', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'Статьи'},
        ),
        migrations.RemoveField(
            model_name='article',
            name='slug',
        ),
    ]
