# Generated by Django 3.1.7 on 2021-03-16 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wikisite', '0002_auto_20210316_1307'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('text', models.TextField(max_length=5000, verbose_name='Текст статьи')),
                ('time_create', models.DateField(auto_now_add=True)),
                ('is_published', models.BooleanField(default=True, verbose_name='ПУбликовать?')),
                ('version', models.IntegerField(default=0)),
                ('old_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wikisite.article')),
            ],
            options={
                'verbose_name': 'Статьи',
            },
        ),
    ]
