# Generated by Django 3.1.7 on 2021-03-16 13:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('wikisite', '0004_delete_newarticle'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='number',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
