# Generated by Django 3.1.7 on 2021-03-16 13:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('wikisite', '0005_article_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='number',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
